package com.mli.mpro.document.enums;

import java.util.HashMap;
import java.util.Map;

public enum FamilyType {
    UNOSWF("OSP"),
    UCOSWF("OSP"),
    UNOSCF("OSP"),
    UCOSCF("OSP"),
    UFINFL("FWP"),
    UFINPL("FWP"),
    UFINRL("FWP"),
    UFINFR("FWP"),
    UFINPR("FWP"),
    UFINRR("FWP"),
    UFWAFL("FWAP"),
    UFWAFR("FWAP"),
    UFWAFS("FWAP"),
    UFWAFW("FWAP"),
    TSFDGS("SFRD"),
    TSFDG1("SFRD"),
    TSFDG2("SFRD"),
    TSFDPS("SFRD"),
    TSFDPL("SFRD"),
    TSFDPR("SFRD"),
    TSFDTS("SFRD"),
    TSFDTL("SFRD"),
    TSFDTR("SFRD"),
    TPFDGS("SFRD"),
    TPFDG1("SFRD"),
    TPFDG2("SFRD"),
    TPFDPS("SFRD"),
    TPFDPL("SFRD"),
    TPFDPR("SFRD"),
    TPFDTS("SFRD"),
    TPFDTL("SFRD"),
    TPFDTR("SFRD"),
    TSJBS("SJB"),
    TSJBR("SJB"),
    TSJBL("SJB"),
    TSGMS("SWAG"),
    TSGML("SWAG"),
    TSGMB("SWAG"),
    TSGRL("SWAG"),
    TSGRB("SWAG"),
    TSGLL("SWAG"),
    TSGLB("SWAG"),
    TSGEL("SWAG"),
    TSGER("SWAG"),
    TSGWL("SWAG"),
    TSGERB("SWAG"),
    TSGELB("SWAG"),
    TPSGMS("SWAG"),
    TPSGML("SWAG"),
    TPSGMB("SWAG"),
    TPSGRL("SWAG"),
    TPSGRB("SWAG"),
    TPSGEL("SWAG"),
    TPSGER("SWAG"),
    TPSERB("SWAG"),
    TNSTES("ste"),
    TNSTER("ste"),
    TNSTEL("ste"),
    TNSTE6("ste"),
    TNSTPS("SSP"),
    TCSTPS("SSP"),
    TNSTPL("SSP"),
    TCSTPL("SSP"),
    TNSTPR("SSP"),
    TCSTPR("SSP"),
    TNST60("SSP"),
    TCST60("SSP"),
    TNSTRS("SSP"),
    TCSTRS("SSP"),
    TNSTRL("SSP"),
    TCSTRL("SSP"),
    TNSTRR("SSP"),
    TNSR60("SSP"),
    TSWPPL("SWPV1"),
    TSWPPR("SWPV1"),
    TSWPVL("SWPV1"),
    TSWPVR("SWPV1"),
    TSWPTL("SWPV3"),
    ESMIL("SWP"),
    TSWPLR("SWPV3"),
    TSWVLR("SWPV3"),
    TSWVTL("SWPV3"),
    TSWPTS("SWPV2"),
    TSWPW1("SWP"),
    TSWPW2("SWP"),
    TSWRW1("SWP"),
    TSTRCS("stpp"),
    TSTRCR("stpp"),
    TSTRCL("stpp"),
    TSTRC6("stpp"),
    TSHRCS("stpp"),
    TSHRCR("stpp"),
    TSHRCL("stpp"),
    TSHRC6("stpp"),
    TSTRBS("stpp"),
    TSTRBR("stpp"),
    TSTRBL("stpp"),
    TSTRB6("stpp"),
    TSTERS("stpp"),
    TSTERL("stpp"),
    TSTER6("stpp"),
    TSHERS("stpp"),
    TSHERL("stpp"),
    TSHER6("stpp"),
    TSTSCS("stpp"),
    TSTSCL("stpp"),
    TSTSC6("stpp"),
    TSHSCS("stpp"),
    TSHSCL("stpp"),
    TSHSC6("stpp"),
    TSTRPS("stpp"),
    TSTRPR("stpp"),
    TSTRPL("stpp"),
    TSTRP6("stpp"),
    TSHRPS("stpp"),
    TSHRPR("stpp"),
    TSHRPL("stpp"),
    TSHRP6("stpp"),
    TSTWLS("stpp"),
    TSTWLL("stpp"),
    TSTWL6("stpp"),
    TSHWLS("stpp"),
    TSHWLL("stpp"),
    TSHWL6("stpp"),
    TSTIPS("stpp"),
    TSTIPR("stpp"),
    TSTIPL("stpp"),
    TSTIP6("stpp"),
    TSHIPS("stpp"),
    TSHIPR("stpp"),
    TSHIPL("stpp"),
    TSHIP6("stpp"),
    TPSRCS("stpp"),
    TPSRCR("stpp"),
    TPSRCL("stpp"),
    TPSRC6("stpp"),
    TPHRCS("stpp"),
    TPHRCR("stpp"),
    TPHRCL("stpp"),
    TPHRC6("stpp"),
    TPSRPS("stpp"),
    TPSRPR("stpp"),
    TPSRPL("stpp"),
    TPSRP6("stpp");


    private final String htmlForm;

    FamilyType(String htmlForm) {
        this.htmlForm = htmlForm;
    }

    public String getHtmlForm() {
        return htmlForm;
    }

    private static final Map<String, FamilyType> productMap = new HashMap<>();

    static {
        for (FamilyType type : values()) {
            productMap.put(type.name(), type);
        }
    }
    public static String getHtmlFormByProductId(String productId) {
        FamilyType type = productMap.get(productId);
        return (type != null) ? type.getHtmlForm() : "";
    }
}