package com.mli.mpro.utils;

import static com.mli.mpro.productRestriction.util.AppConstants.*;

public enum MaskType {
  MASK_ALL(MASK_ALL_REGEX),
  AMOUNT(MASK_ALL_REGEX),
  GENDER(MASK_ALL_REGEX),
  NAME(SHOW_FIRST_LAST_DIGITS_REGEX),
  ADDRESS_PROOF_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  CKYC_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  PINCODE(SHOW_LAST_TWO_DIGITS_REGEX),
  MOBILE(SHOW_LAST_TWO_DIGITS_REGEX),
  EMAIL(SHOW_FIRST_LAST_DIGITS_REGEX),
  FIRST_NAME(SHOW_FIRST_DIGIT_REGEX),
  ID_PROOF_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  MIDDLE_NAME(MASK_ALL_REGEX),
  LAST_NAME(SHOW_LAST_DIGIT_REGEX),
  AADHAAR_NUM(SHOW_LAST_FOUR_DIGITS_REGEX),
  DOB(MASK_ALL_REGEX),
  PLACE_OF_BIRTH(SHOW_FIRST_LAST_DIGITS_REGEX),
  COUNTRY_OF_BIRTH(SHOW_FIRST_LAST_DIGITS_REGEX),
  PASSPORT(SHOW_LAST_TWO_DIGITS_REGEX),
  PAN_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  ADDRESS(SHOW_FIRST_LAST_DIGITS_REGEX),
  POLICY_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  CHEQUE_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_ACC_NUM(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_ACC_HOLDER_NAME(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_MICR(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_IFSC(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_NAME(SHOW_LAST_TWO_DIGITS_REGEX),
  BANK_BRANCH_NAME(SHOW_LAST_TWO_DIGITS_REGEX),
  BRANCH_CODE(SHOW_LAST_TWO_DIGITS_REGEX);

  private final String value;

  MaskType(String val) {
    value = val;
  }

  public String getValue() {
    return value;
  }
}
